import * as fuseReducers from "./fuse";
import {
  closeDialog,
  openDialog,
  selectFuseDialogOptions,
  selectFuseDialogState,
} from "./fuse/dialogSlice";
import {
  hideMessage,
  selectFuseMessageOptions,
  selectFuseMessageState,
  showMessage,
} from "./fuse/messageSlice";
import {
  navbarClose,
  navbarCloseFolded,
  navbarCloseMobile,
  navbarOpen,
  navbarOpenFolded,
  navbarOpenMobile,
  navbarToggle,
  navbarToggleFolded,
  navbarToggleMobile,
  selectFuseNavbar,
} from "./fuse/navbarSlice";
import {
  appendNavigationItem,
  prependNavigationItem,
  removeNavigationItem,
  resetNavigation,
  selectFlatNavigation,
  selectNavigation,
  selectNavigationAll,
  selectNavigationIds,
  selectNavigationItemById,
  setNavigation,
  updateNavigationItem,
} from "./fuse/navigationSlice";
import {
  changeFuseTheme,
  generateSettings,
  selectContrastMainTheme,
  selectFooterTheme,
  selectFooterThemeDark,
  selectFooterThemeLight,
  selectFuseCurrentLayoutConfig,
  selectFuseCurrentSettings,
  selectFuseDefaultSettings,
  selectFuseThemesSettings,
  selectMainTheme,
  selectMainThemeDark,
  selectMainThemeLight,
  selectNavbarTheme,
  selectNavbarThemeDark,
  selectNavbarThemeLight,
  selectToolbarTheme,
  selectToolbarThemeDark,
  selectToolbarThemeLight,
  setDefaultSettings,
  setSettings,
} from "./fuse/settingsSlice";
import {
  changeLanguage,
  default as i18nSlice,
  selectCurrentLanguage,
  selectCurrentLanguageDirection,
  selectCurrentLanguageId,
  selectLanguages,
} from "./i18nSlice";
import { default as createReducer } from "./rootReducer";
import { default as store } from "./store";
import {
  default as userSliceReducer,
  logoutUser,
  selectUser,
  selectUserShortcuts,
  setUser,
  updateUserData,
  updateUserSettings,
  updateUserShortcuts,
  userLoggedOut,
} from "./userSlice";
import { default as withReducer } from "./withReducer";

export {
  i18nSlice,
  createReducer,
  changeLanguage,
  selectCurrentLanguageId,
  selectLanguages,
  selectCurrentLanguageDirection,
  selectCurrentLanguage,
  store,
  userSliceReducer,
  setUser,
  updateUserSettings,
  updateUserShortcuts,
  logoutUser,
  updateUserData,
  userLoggedOut,
  selectUser,
  selectUserShortcuts,
  withReducer,
  fuseReducers,
  openDialog,
  closeDialog,
  selectFuseDialogState,
  selectFuseDialogOptions,
  hideMessage,
  showMessage,
  selectFuseMessageState,
  selectFuseMessageOptions,
  navbarToggleFolded,
  navbarOpenFolded,
  navbarCloseFolded,
  navbarOpen,
  navbarClose,
  navbarToggle,
  navbarOpenMobile,
  navbarCloseMobile,
  navbarToggleMobile,
  selectFuseNavbar,
  appendNavigationItem,
  prependNavigationItem,
  removeNavigationItem,
  updateNavigationItem,
  selectNavigationAll,
  selectNavigationIds,
  selectNavigationItemById,
  setNavigation,
  resetNavigation,
  selectNavigation,
  selectFlatNavigation,
  changeFuseTheme,
  generateSettings,
  setDefaultSettings,
  selectContrastMainTheme,
  selectMainTheme,
  selectMainThemeDark,
  selectMainThemeLight,
  selectNavbarTheme,
  selectNavbarThemeDark,
  selectNavbarThemeLight,
  selectToolbarTheme,
  selectToolbarThemeDark,
  selectToolbarThemeLight,
  selectFooterTheme,
  selectFooterThemeDark,
  selectFooterThemeLight,
  selectFuseCurrentSettings,
  selectFuseCurrentLayoutConfig,
  selectFuseDefaultSettings,
  selectFuseThemesSettings,
  setSettings,
};
