on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [closed]
    branches:
      - main

name: 🚀 Nahrať na FTP server - TEST
jobs:
  web-deploy:
    name: 🚀 Nahrať na FTP server - TEST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 🚚 NPM INSTALL
        uses: actions/checkout@v2

      - name: Použiť Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set build date
        run: |
          BUILD_DATE=$(jq -n 'now | strftime("%Y-%m-%d %H:%M:%S")')
          jq ". + {\"buildDate\": ${BUILD_DATE}}" package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Add buildEnv string
        run: |
          jq '. + {"buildEnv": "test"}' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: 🔨 NPM RUN BUILD
        run: |
          npm install
          npm run build
      - name: 📂 NAHRAŤ NA FTP SERVER
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./build/
          server-dir: ${{secrets.FTP_SERVER}}/sub/portal/
          port: 21
          protocol: ftp
          timeout: 200000
